name: Profile

on:
  schedule: [{ cron: '0 */12 * * *' }]  # 每 12 小时更新一次
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          committer_token: ${{ secrets.token }}
          token: ${{ secrets.token }}
          base: header, repositories
          plugin_lines: yes

  snk:
    needs: [metrics]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.token }}
    steps:
      - name: Setup Information
        run: |
          git config --global user.email idoingno@163.com
          git config --global user.name idoingno
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}
      - name: Update SNK
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-snake.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            github-snake-dark.svg?palette=github-dark&color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      - name: Push to main
        run: |
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Update SNK"
            git pull --rebase origin main
            git push origin main
          else
            echo "No Change, Bye bye!"
          fi
